version: '3.8'
services:
  db:
    container_name: postgres
    init: true
    build: 
      context: ..
      dockerfile: ../postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    ports:
      - "5432:5432"
    volumes:
      - ../postgres/db-store:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  db-store:

networks:
  app-network:
